<a href="https://colab.research.google.com/github/tnwls6865/Creative_Masters/blob/main/week5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Creative Masters


### Chat GPT
https://openai.com/blog/chatgpt

#### 간단한 계산기

In [ ]:
# 함수 정의
def add(x, y):
    return x + y

def subtract(x, y):
    return x - y

def multiply(x, y):
    return x * y

def divide(x, y):
    return x / y

# 사용자 입력 받기
print("사칙연산 계산기입니다.")
print("사용 가능한 연산: +, -, *, /")
num1 = float(input("첫 번째 숫자를 입력하세요: "))
num2 = float(input("두 번째 숫자를 입력하세요: "))
operator = input("연산자를 입력하세요: ")

# 계산 수행
if operator == "+":
    print(num1, "+", num2, "=", add(num1, num2))

elif operator == "-":
    print(num1, "-", num2, "=", subtract(num1, num2))

elif operator == "*":
    print(num1, "*", num2, "=", multiply(num1, num2))

elif operator == "/":
    print(num1, "/", num2, "=", divide(num1, num2))

else:
    print("올바른 연산자를 입력하세요.")


사칙연산 계산기입니다.
사용 가능한 연산: +, -, *, /
첫 번째 숫자를 입력하세요: 5
두 번째 숫자를 입력하세요: 10
연산자를 입력하세요: /
5.0 / 10.0 = 0.5


##### python 에서 numpy array 연산 예시 보여줘 

In [ ]:
import numpy as np

# 1차원 배열 생성하기
a = np.array([1, 2, 3])

# 2차원 배열 생성하기
b = np.array([[1, 2, 3], [4, 5, 6]])

# 3차원 배열 생성하기
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [ ]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# 배열 더하기
c = a + b  # [5, 7, 9]

# 배열 빼기
d = a - b  # [-3, -3, -3]

# 배열 곱하기 (요소별 곱셈)
e = a * b  # [4, 10, 18]

# 배열 나누기 (요소별 나눗셈)
f = b / a  # [4.0, 2.5, 2.0]

# 배열 제곱
g = a ** 2  # [1, 4, 9]

# 배열 비교 (요소별 비교)
h = a > b  # [False, False, False]

In [ ]:
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)
print(h)

[1 2 3]
[4 5 6]
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[4.  2.5 2. ]
[1 4 9]
[False False False]


##### python으로 knn코드 짜줘

In [ ]:
import numpy as np

# 거리 계산 함수
def euclidean_distance(x1, x2):
    return np.sqrt(np.sum((x1 - x2)**2))

class KNN:
    def __init__(self, k=3):
        self.k = k

    def fit(self, X, y):
        self.X_train = X
        self.y_train = y

    def predict(self, X):
        y_pred = [self._predict(x) for x in X]
        return np.array(y_pred)

    def _predict(self, x):
        # 거리 계산
        distances = [euclidean_distance(x, x_train) for x_train in self.X_train]

        # k개의 최근접 이웃 구하기
        k_indices = np.argsort(distances)[:self.k]
        k_nearest_labels = [self.y_train[i] for i in k_indices]

        # 가장 투표를 많이 받은 레이블 반환
        most_common = Counter(k_nearest_labels).most_common(1)
        return most_common[0][0]


##### pytorch cifar10 dataset으로 knn학습하는 코드 짜줘

In [2]:
import torch
import torchvision
import numpy as np
from collections import Counter

# CIFAR10 데이터셋 다운로드 및 전처리
transform = torchvision.transforms.Compose([
    torchvision.transforms.ToTensor(),
    torchvision.transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
])
trainset = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=transform)
testset = torchvision.datasets.CIFAR10(root='./data', train=False, download=True, transform=transform)

# 학습 데이터와 테스트 데이터로 나누기
trainloader = torch.utils.data.DataLoader(trainset, batch_size=50000, shuffle=False)
testloader = torch.utils.data.DataLoader(testset, batch_size=10000, shuffle=False)

# 데이터 로드 및 전처리 함수 정의
def preprocess_data(dataloader):
    inputs = []
    labels = []
    for batch in dataloader:
        input_batch, label_batch = batch
        input_batch = input_batch.view(input_batch.shape[0], -1)
        inputs.append(input_batch.numpy())
        labels.append(label_batch.numpy())
    inputs = np.concatenate(inputs, axis=0)
    labels = np.concatenate(labels, axis=0)
    return inputs, labels

# 데이터 전처리
X_train, y_train = preprocess_data(trainloader)
X_test, y_test = preprocess_data(testloader)

# 거리 계산 함수
def euclidean_distance(x1, x2):
    return np.sqrt(np.sum((x1 - x2)**2))

class KNN:
    def __init__(self, k=3):
        self.k = k

    def fit(self, X, y):
        self.X_train = X
        self.y_train = y

    def predict(self, X):
        y_pred = [self._predict(x) for x in X]
        return np.array(y_pred)

    def _predict(self, x):
        # 거리 계산
        distances = [euclidean_distance(x, x_train) for x_train in self.X_train]

        # k개의 최근접 이웃 구하기
        k_indices = np.argsort(distances)[:self.k]
        k_nearest_labels = [self.y_train[i] for i in k_indices]

        # 가장 투표를 많이 받은 레이블 반환
        most_common = Counter(k_nearest_labels).most_common(1)
        return most_common[0][0]


Files already downloaded and verified
Files already downloaded and verified


In [6]:
# KNN 모델 생성 및 학습
knn = KNN(k=3)
knn.fit(X_train, y_train)

# 테스트 데이터로 예측하기
y_pred = knn.predict(X_test[:50])

# 정확도 계산하기
accuracy = np.mean(y_pred == y_test[:50])
print("Accuracy:", accuracy)

Accuracy: 0.26


pytorch로 linear classifier코드 짜줘

In [7]:
import torch
import torch.nn as nn
import torch.optim as optim
from torchvision import datasets, transforms

# 1. 데이터 로드
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.1307,), (0.3081,))
])

trainset = datasets.MNIST('./data/', train=True, download=True, transform=transform)
trainloader = torch.utils.data.DataLoader(trainset, batch_size=64, shuffle=True)

testset = datasets.MNIST('./data/', train=False, download=True, transform=transform)
testloader = torch.utils.data.DataLoader(testset, batch_size=64, shuffle=True)

# 2. 모델 아키텍처 정의
class LinearClassifier(nn.Module):
    def __init__(self):
        super(LinearClassifier, self).__init__()
        self.fc = nn.Linear(784, 10)
        
    def forward(self, x):
        x = x.view(x.size(0), -1)
        x = self.fc(x)
        return x

model = LinearClassifier()

# 3. 손실 함수 선택
criterion = nn.CrossEntropyLoss()

# 4. 최적화 알고리즘 선택
optimizer = optim.SGD(model.parameters(), lr=0.01, momentum=0.5)

# 5. 모델 학습
def train(model, trainloader, criterion, optimizer):
    model.train()
    for batch_idx, (data, target) in enumerate(trainloader):
        optimizer.zero_grad()
        output = model(data)
        loss = criterion(output, target)
        loss.backward()
        optimizer.step()

def test(model, testloader, criterion):
    model.eval()
    test_loss = 0
    correct = 0
    with torch.no_grad():
        for data, target in testloader:
            output = model(data)
            test_loss += criterion(output, target).item()
            pred = output.argmax(dim=1, keepdim=True)
            correct += pred.eq(target.view_as(pred)).sum().item()

    test_loss /= len(testloader.dataset)

    print('\nTest set: Average loss: {:.4f}, Accuracy: {}/{} ({:.0f}%)\n'.format(
        test_loss, correct, len(testloader.dataset),
        100. * correct / len(testloader.dataset)))

epochs = 10
for epoch in range(1, epochs + 1):
    train(model, trainloader, criterion, optimizer)
    test(model, testloader, criterion)

# 6. 모델 평가
test(model, testloader, criterion)


100%|██████████| 9912422/9912422 [00:00<00:00, 94698158.33it/s]


Extracting ./data/MNIST/raw/train-images-idx3-ubyte.gz to ./data/MNIST/raw



100%|██████████| 28881/28881 [00:00<00:00, 17808834.73it/s]


Extracting ./data/MNIST/raw/train-labels-idx1-ubyte.gz to ./data/MNIST/raw



100%|██████████| 1648877/1648877 [00:00<00:00, 28550692.71it/s]


Extracting ./data/MNIST/raw/t10k-images-idx3-ubyte.gz to ./data/MNIST/raw



100%|██████████| 4542/4542 [00:00<00:00, 9942864.70it/s]


Extracting ./data/MNIST/raw/t10k-labels-idx1-ubyte.gz to ./data/MNIST/raw


Test set: Average loss: 0.0048, Accuracy: 9124/10000 (91%)


Test set: Average loss: 0.0046, Accuracy: 9177/10000 (92%)


Test set: Average loss: 0.0044, Accuracy: 9207/10000 (92%)


Test set: Average loss: 0.0044, Accuracy: 9207/10000 (92%)


Test set: Average loss: 0.0044, Accuracy: 9195/10000 (92%)


Test set: Average loss: 0.0044, Accuracy: 9237/10000 (92%)


Test set: Average loss: 0.0043, Accuracy: 9204/10000 (92%)


Test set: Average loss: 0.0044, Accuracy: 9199/10000 (92%)


Test set: Average loss: 0.0043, Accuracy: 9239/10000 (92%)


Test set: Average loss: 0.0043, Accuracy: 9222/10000 (92%)


Test set: Average loss: 0.0043, Accuracy: 9222/10000 (92%)



In [8]:
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision.datasets as datasets
import torchvision.transforms as transforms

# 하이퍼파라미터 설정
batch_size = 64
learning_rate = 0.001
num_epochs = 10

# 데이터셋 불러오기 및 전처리
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.1307,), (0.3081,))
])

train_dataset = datasets.MNIST(root='./data', train=True, download=True, transform=transform)
test_dataset = datasets.MNIST(root='./data', train=False, download=True, transform=transform)

train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

# 모델 정의
class CNN(nn.Module):
    def __init__(self):
        super(CNN, self).__init__()
        self.conv1 = nn.Conv2d(1, 10, kernel_size=5)
        self.pool = nn.MaxPool2d(kernel_size=2)
        self.conv2 = nn.Conv2d(10, 20, kernel_size=5)
        self.fc1 = nn.Linear(320, 50)
        self.fc2 = nn.Linear(50, 10)

    def forward(self, x):
        x = self.pool(torch.relu(self.conv1(x)))
        x = self.pool(torch.relu(self.conv2(x)))
        x = x.view(-1, 320)
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x

# 모델 초기화
model = CNN()

# 손실 함수 및 최적화 알고리즘 정의
criterion = nn.CrossEntropyLoss()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

# 모델 학습
for epoch in range(num_epochs):
    for batch_idx, (data, targets) in enumerate(train_loader):
        optimizer.zero_grad()
        
        # 순전파
        outputs = model(data)
        loss = criterion(outputs, targets)
        
        # 역전파 및 가중치 업데이트
        loss.backward()
        optimizer.step()
        
        # 로그 출력
        if batch_idx % 100 == 0:
            print('Epoch [{}/{}], Batch [{}/{}], Loss: {:.4f}'
                  .format(epoch+1, num_epochs, batch_idx+1, len(train_loader), loss.item()))

# 모델 평가
with torch.no_grad():
    correct = 0
    total = 0
    for data, targets in test_loader:
        outputs = model(data)
        _, predicted = torch.max(outputs.data, 1)
        total += targets.size(0)
        correct += (predicted == targets).sum().item()

    print('Test Accuracy: {:.2f}%'.format(100 * correct / total))


Epoch [1/10], Batch [1/938], Loss: 2.3327
Epoch [1/10], Batch [101/938], Loss: 0.2711
Epoch [1/10], Batch [201/938], Loss: 0.1644
Epoch [1/10], Batch [301/938], Loss: 0.2820
Epoch [1/10], Batch [401/938], Loss: 0.5163
Epoch [1/10], Batch [501/938], Loss: 0.1074
Epoch [1/10], Batch [601/938], Loss: 0.1975
Epoch [1/10], Batch [701/938], Loss: 0.1146
Epoch [1/10], Batch [801/938], Loss: 0.0947
Epoch [1/10], Batch [901/938], Loss: 0.0259
Epoch [2/10], Batch [1/938], Loss: 0.0448
Epoch [2/10], Batch [101/938], Loss: 0.0509
Epoch [2/10], Batch [201/938], Loss: 0.1146
Epoch [2/10], Batch [301/938], Loss: 0.0801
Epoch [2/10], Batch [401/938], Loss: 0.0522
Epoch [2/10], Batch [501/938], Loss: 0.2500
Epoch [2/10], Batch [601/938], Loss: 0.0252
Epoch [2/10], Batch [701/938], Loss: 0.0463
Epoch [2/10], Batch [801/938], Loss: 0.0908
Epoch [2/10], Batch [901/938], Loss: 0.1231
Epoch [3/10], Batch [1/938], Loss: 0.0714
Epoch [3/10], Batch [101/938], Loss: 0.0433
Epoch [3/10], Batch [201/938], Loss: 0

In [3]:
import torch
import torch.nn as nn
import torch.optim as optim
import torchvision.datasets as datasets
import torchvision.transforms as transforms

# 하이퍼파라미터 설정
batch_size = 64
learning_rate = 0.001
num_epochs = 10

# 데이터셋 불러오기 및 전처리
transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.1307,), (0.3081,))
])

train_dataset = datasets.MNIST(root='./data', train=True, download=True, transform=transform)
test_dataset = datasets.MNIST(root='./data', train=False, download=True, transform=transform)

train_loader = torch.utils.data.DataLoader(train_dataset, batch_size=batch_size, shuffle=True)
test_loader = torch.utils.data.DataLoader(test_dataset, batch_size=batch_size, shuffle=False)

# 모델 정의
class CNN(nn.Module):
    def __init__(self):
        super(CNN, self).__init__()
        self.conv1 = nn.Conv2d(1, 10, kernel_size=5)
        self.pool = nn.MaxPool2d(kernel_size=2)
        self.conv2 = nn.Conv2d(10, 20, kernel_size=5)
        self.fc1 = nn.Linear(320, 50)
        self.fc2 = nn.Linear(50, 10)

    def forward(self, x):
        x = self.pool(torch.relu(self.conv1(x)))
        x = self.pool(torch.relu(self.conv2(x)))
        x = x.view(-1, 320)
        x = torch.relu(self.fc1(x))
        x = self.fc2(x)
        return x

# 모델 초기화
model = CNN()
model = model.cuda()

# 손실 함수 및 최적화 알고리즘 정의
criterion = nn.CrossEntropyLoss().cuda()
optimizer = optim.Adam(model.parameters(), lr=learning_rate)

# 모델 학습
for epoch in range(num_epochs):
    for batch_idx, (data, targets) in enumerate(train_loader):
        optimizer.zero_grad()
        
        # 순전파
        outputs = model(data.cuda())
        loss = criterion(outputs, targets.cuda())
        
        # 역전파 및 가중치 업데이트
        loss.backward()
        optimizer.step()
        
        # 로그 출력
        if batch_idx % 100 == 0:
            print('Epoch [{}/{}], Batch [{}/{}], Loss: {:.4f}'
                  .format(epoch+1, num_epochs, batch_idx+1, len(train_loader), loss.item()))

# 모델 평가
with torch.no_grad():
    correct = 0
    total = 0
    for data, targets in test_loader:
        outputs = model(data.cuda())
        _, predicted = torch.max(outputs.data, 1)
        total += targets.size(0)
        correct += (predicted == targets).sum().item()

    print('Test Accuracy: {:.2f}%'.format(100 * correct / total))


Epoch [1/10], Batch [1/938], Loss: 2.3195
Epoch [1/10], Batch [101/938], Loss: 0.2572
Epoch [1/10], Batch [201/938], Loss: 0.1884
Epoch [1/10], Batch [301/938], Loss: 0.1980
Epoch [1/10], Batch [401/938], Loss: 0.1768
Epoch [1/10], Batch [501/938], Loss: 0.0616
Epoch [1/10], Batch [601/938], Loss: 0.1251
Epoch [1/10], Batch [701/938], Loss: 0.0102
Epoch [1/10], Batch [801/938], Loss: 0.0178
Epoch [1/10], Batch [901/938], Loss: 0.0679
Epoch [2/10], Batch [1/938], Loss: 0.0538
Epoch [2/10], Batch [101/938], Loss: 0.0364
Epoch [2/10], Batch [201/938], Loss: 0.1704
Epoch [2/10], Batch [301/938], Loss: 0.0571
Epoch [2/10], Batch [401/938], Loss: 0.0366
Epoch [2/10], Batch [501/938], Loss: 0.0602
Epoch [2/10], Batch [601/938], Loss: 0.0083
Epoch [2/10], Batch [701/938], Loss: 0.0501
Epoch [2/10], Batch [801/938], Loss: 0.0280
Epoch [2/10], Batch [901/938], Loss: 0.0192
Epoch [3/10], Batch [1/938], Loss: 0.0111
Epoch [3/10], Batch [101/938], Loss: 0.0117
Epoch [3/10], Batch [201/938], Loss: 0

RuntimeError: ignored