<a href="https://colab.research.google.com/github/tnwls6865/Creative_Masters/blob/main/week5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Creative Masters


### Chat GPT
https://openai.com/blog/chatgpt

#### 간단한 계산기

In [ ]:
# 함수 정의
def add(x, y):
    return x + y

def subtract(x, y):
    return x - y

def multiply(x, y):
    return x * y

def divide(x, y):
    return x / y

# 사용자 입력 받기
print("사칙연산 계산기입니다.")
print("사용 가능한 연산: +, -, *, /")
num1 = float(input("첫 번째 숫자를 입력하세요: "))
num2 = float(input("두 번째 숫자를 입력하세요: "))
operator = input("연산자를 입력하세요: ")

# 계산 수행
if operator == "+":
    print(num1, "+", num2, "=", add(num1, num2))

elif operator == "-":
    print(num1, "-", num2, "=", subtract(num1, num2))

elif operator == "*":
    print(num1, "*", num2, "=", multiply(num1, num2))

elif operator == "/":
    print(num1, "/", num2, "=", divide(num1, num2))

else:
    print("올바른 연산자를 입력하세요.")


사칙연산 계산기입니다.
사용 가능한 연산: +, -, *, /
첫 번째 숫자를 입력하세요: 5
두 번째 숫자를 입력하세요: 10
연산자를 입력하세요: /
5.0 / 10.0 = 0.5


##### python 에서 numpy array 연산 예시 보여줘 

In [2]:
import numpy as np

# 1차원 배열 생성하기
a = np.array([1, 2, 3])

# 2차원 배열 생성하기
b = np.array([[1, 2, 3], [4, 5, 6]])

# 3차원 배열 생성하기
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])

In [3]:
import numpy as np

a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# 배열 더하기
c = a + b  # [5, 7, 9]

# 배열 빼기
d = a - b  # [-3, -3, -3]

# 배열 곱하기 (요소별 곱셈)
e = a * b  # [4, 10, 18]

# 배열 나누기 (요소별 나눗셈)
f = b / a  # [4.0, 2.5, 2.0]

# 배열 제곱
g = a ** 2  # [1, 4, 9]

# 배열 비교 (요소별 비교)
h = a > b  # [False, False, False]

In [4]:
print(a)
print(b)
print(c)
print(d)
print(e)
print(f)
print(g)
print(h)

[1 2 3]
[4 5 6]
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[4.  2.5 2. ]
[1 4 9]
[False False False]


##### python으로 knn코드 짜줘

In [6]:
import numpy as np

# 거리 계산 함수
def euclidean_distance(x1, x2):
    return np.sqrt(np.sum((x1 - x2)**2))

class KNN:
    def __init__(self, k=3):
        self.k = k

    def fit(self, X, y):
        self.X_train = X
        self.y_train = y

    def predict(self, X):
        y_pred = [self._predict(x) for x in X]
        return np.array(y_pred)

    def _predict(self, x):
        # 거리 계산
        distances = [euclidean_distance(x, x_train) for x_train in self.X_train]

        # k개의 최근접 이웃 구하기
        k_indices = np.argsort(distances)[:self.k]
        k_nearest_labels = [self.y_train[i] for i in k_indices]

        # 가장 투표를 많이 받은 레이블 반환
        most_common = Counter(k_nearest_labels).most_common(1)
        return most_common[0][0]


##### pytorch cifar10 dataset으로 knn학습하는 코드 짜줘

In [ ]:
import torch
import torchvision
import numpy as np
from collections import Counter

# CIFAR10 데이터셋 다운로드 및 전처리
transform = torchvision.transforms.Compose([
    torchvision.transforms.ToTensor(),
    torchvision.transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
])
trainset = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=transform)
testset = torchvision.datasets.CIFAR10(root='./data', train=False, download=True, transform=transform)

# 학습 데이터와 테스트 데이터로 나누기
trainloader = torch.utils.data.DataLoader(trainset, batch_size=50000, shuffle=False)
testloader = torch.utils.data.DataLoader(testset, batch_size=10000, shuffle=False)

# 데이터 로드 및 전처리 함수 정의
def preprocess_data(dataloader):
    inputs = []
    labels = []
    for batch in dataloader:
        input_batch, label_batch = batch
        input_batch = input_batch.view(input_batch.shape[0], -1)
        inputs.append(input_batch.numpy())
        labels.append(label_batch.numpy())
    inputs = np.concatenate(inputs, axis=0)
    labels = np.concatenate(labels, axis=0)
    return inputs, labels

# 데이터 전처리
X_train, y_train = preprocess_data(trainloader)
X_test, y_test = preprocess_data(testloader)

# 거리 계산 함수
def euclidean_distance(x1, x2):
    return np.sqrt(np.sum((x1 - x2)**2))

class KNN:
    def __init__(self, k=3):
        self.k = k

    def fit(self, X, y):
        self.X_train = X
        self.y_train = y

    def predict(self, X):
        y_pred = [self._predict(x) for x in X]
        return np.array(y_pred)

    def _predict(self, x):
        # 거리 계산
        distances = [euclidean_distance(x, x_train) for x_train in self.X_train]

        # k개의 최근접 이웃 구하기
        k_indices = np.argsort(distances)[:self.k]
        k_nearest_labels = [self.y_train[i] for i in k_indices]

        # 가장 투표를 많이 받은 레이블 반환
        most_common = Counter(k_nearest_labels).most_common(1)
        return most_common[0][0]

# KNN 모델 생성 및 학습
knn = KNN(k=5)
knn.fit(X_train, y_train)

# 테스트 데이터로 예측하기
y_pred = knn.predict(X_test)

# 정확도 계산하기
accuracy = np.mean(y_pred == y_test)
print("Accuracy:", accuracy)

100%|██████████| 170498071/170498071 [00:04<00:00, 37967092.45it/s]


Extracting ./data/cifar-10-python.tar.gz to ./data
Files already downloaded and verified
